//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizedText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account ID.
        /// </summary>
        internal static string account_id {
            get {
                return ResourceManager.GetString("account_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account info.
        /// </summary>
        internal static string account_info {
            get {
                return ResourceManager.GetString("account_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alter amount.
        /// </summary>
        internal static string alter_amount {
            get {
                return ResourceManager.GetString("alter_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string available {
            get {
                return ResourceManager.GetString("available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank transfer.
        /// </summary>
        internal static string bank_transfer {
            get {
                return ResourceManager.GetString("bank_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay by bank transfer..
        /// </summary>
        internal static string bank_transfer_description {
            get {
                return ResourceManager.GetString("bank_transfer_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black &amp; White.
        /// </summary>
        internal static string black_white {
            get {
                return ResourceManager.GetString("black_white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change account data.
        /// </summary>
        internal static string change_account_data {
            get {
                return ResourceManager.GetString("change_account_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your bank.
        /// </summary>
        internal static string choose_bank {
            get {
                return ResourceManager.GetString("choose_bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies uw bank.
        /// </summary>
        internal static string choose_bank_prompt {
            get {
                return ResourceManager.GetString("choose_bank_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your payment method:.
        /// </summary>
        internal static string choose_payment_method {
            get {
                return ResourceManager.GetString("choose_payment_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your order and shipping address.
        /// </summary>
        internal static string confirm_order_address {
            get {
                return ResourceManager.GetString("confirm_order_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the account creation page! Please fill in the fields below.
        /// </summary>
        internal static string createaccount_welcome {
            get {
                return ResourceManager.GetString("createaccount_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string create_account {
            get {
                return ResourceManager.GetString("create_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        internal static string crop {
            get {
                return ResourceManager.GetString("crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send mail to.
        /// </summary>
        internal static string error_cant_send_mail {
            get {
                return ResourceManager.GetString("error_cant_send_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your code.
        /// </summary>
        internal static string error_enter_code {
            get {
                return ResourceManager.GetString("error_enter_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail.
        /// </summary>
        internal static string error_enter_email {
            get {
                return ResourceManager.GetString("error_enter_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        internal static string error_enter_password {
            get {
                return ResourceManager.GetString("error_enter_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a search term.
        /// </summary>
        internal static string error_enter_search_term {
            get {
                return ResourceManager.GetString("error_enter_search_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong e-mail address or password.
        /// </summary>
        internal static string error_login {
            get {
                return ResourceManager.GetString("error_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Image found, please the contact administrator.
        /// </summary>
        internal static string error_no_image_found {
            get {
                return ResourceManager.GetString("error_no_image_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown user type.
        /// </summary>
        internal static string error_user_type {
            get {
                return ResourceManager.GetString("error_user_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code you entered is not valid.
        /// </summary>
        internal static string error_wrong_code {
            get {
                return ResourceManager.GetString("error_wrong_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        internal static string error_wrong_email {
            get {
                return ResourceManager.GetString("error_wrong_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        internal static string finance {
            get {
                return ResourceManager.GetString("finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go!.
        /// </summary>
        internal static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Checkout.
        /// </summary>
        internal static string google_checkout {
            get {
                return ResourceManager.GetString("google_checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast checkout through Google.
        /// </summary>
        internal static string google_checkout_description {
            get {
                return ResourceManager.GetString("google_checkout_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google-checkout payment.
        /// </summary>
        internal static string google_checkout_payment {
            get {
                return ResourceManager.GetString("google_checkout_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string go_back {
            get {
                return ResourceManager.GetString("go_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group pictures.
        /// </summary>
        internal static string group_pictures {
            get {
                return ResourceManager.GetString("group_pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House number.
        /// </summary>
        internal static string house_number {
            get {
                return ResourceManager.GetString("house_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN.
        /// </summary>
        internal static string IBAN {
            get {
                return ResourceManager.GetString("IBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDeal.
        /// </summary>
        internal static string ideal {
            get {
                return ResourceManager.GetString("ideal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most used payment method in the Netherlands.
        /// </summary>
        internal static string ideal_description {
            get {
                return ResourceManager.GetString("ideal_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ideal_payment {
            get {
                return ResourceManager.GetString("ideal_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image preview.
        /// </summary>
        internal static string image_preview {
            get {
                return ResourceManager.GetString("image_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your mail has been sent to.
        /// </summary>
        internal static string mail_sent {
            get {
                return ResourceManager.GetString("mail_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money owed.
        /// </summary>
        internal static string money_owed {
            get {
                return ResourceManager.GetString("money_owed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        internal static string my_account {
            get {
                return ResourceManager.GetString("my_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Codes.
        /// </summary>
        internal static string my_codes {
            get {
                return ResourceManager.GetString("my_codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Products.
        /// </summary>
        internal static string my_products {
            get {
                return ResourceManager.GetString("my_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogone.
        /// </summary>
        internal static string ogone {
            get {
                return ResourceManager.GetString("ogone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An ingenico company.
        /// </summary>
        internal static string ogone_description {
            get {
                return ResourceManager.GetString("ogone_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ogone_payment {
            get {
                return ResourceManager.GetString("ogone_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string orders {
            get {
                return ResourceManager.GetString("orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string order_code {
            get {
                return ResourceManager.GetString("order_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or insert your order code.
        /// </summary>
        internal static string order_code_title {
            get {
                return ResourceManager.GetString("order_code_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order history.
        /// </summary>
        internal static string order_history {
            get {
                return ResourceManager.GetString("order_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        internal static string order_id {
            get {
                return ResourceManager.GetString("order_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string order_image {
            get {
                return ResourceManager.GetString("order_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order info.
        /// </summary>
        internal static string order_info {
            get {
                return ResourceManager.GetString("order_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Check.
        /// </summary>
        internal static string payment_check {
            get {
                return ResourceManager.GetString("payment_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment type.
        /// </summary>
        internal static string payment_type {
            get {
                return ResourceManager.GetString("payment_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        internal static string paypal {
            get {
                return ResourceManager.GetString("paypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A faster, safer way to pay.
        /// </summary>
        internal static string paypal_description {
            get {
                return ResourceManager.GetString("paypal_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal info.
        /// </summary>
        internal static string personal_info {
            get {
                return ResourceManager.GetString("personal_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string phone_number {
            get {
                return ResourceManager.GetString("phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographer ID.
        /// </summary>
        internal static string photographer_id {
            get {
                return ResourceManager.GetString("photographer_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo ID.
        /// </summary>
        internal static string photo_id {
            get {
                return ResourceManager.GetString("photo_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        internal static string pictures {
            get {
                return ResourceManager.GetString("pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place order.
        /// </summary>
        internal static string place_order {
            get {
                return ResourceManager.GetString("place_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Description.
        /// </summary>
        internal static string product_description {
            get {
                return ResourceManager.GetString("product_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        internal static string product_id {
            get {
                return ResourceManager.GetString("product_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        internal static string product_type {
            get {
                return ResourceManager.GetString("product_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase ID.
        /// </summary>
        internal static string purchase_id {
            get {
                return ResourceManager.GetString("purchase_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string remember_me {
            get {
                return ResourceManager.GetString("remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-order.
        /// </summary>
        internal static string reorder {
            get {
                return ResourceManager.GetString("reorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string save_changes {
            get {
                return ResourceManager.GetString("save_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for....
        /// </summary>
        internal static string search_for {
            get {
                return ResourceManager.GetString("search_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your bank.
        /// </summary>
        internal static string select_bank_prompt {
            get {
                return ResourceManager.GetString("select_bank_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepia.
        /// </summary>
        internal static string sepia {
            get {
                return ResourceManager.GetString("sepia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship orders.
        /// </summary>
        internal static string ship_orders {
            get {
                return ResourceManager.GetString("ship_orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping cart.
        /// </summary>
        internal static string shopping_cart {
            get {
                return ResourceManager.GetString("shopping_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string sign_in {
            get {
                return ResourceManager.GetString("sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in-.
        /// </summary>
        internal static string sign_in_title {
            get {
                return ResourceManager.GetString("sign_in_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string stock {
            get {
                return ResourceManager.GetString("stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock overview.
        /// </summary>
        internal static string stock_overview {
            get {
                return ResourceManager.GetString("stock_overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street name.
        /// </summary>
        internal static string street_name {
            get {
                return ResourceManager.GetString("street_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times used.
        /// </summary>
        internal static string times_used {
            get {
                return ResourceManager.GetString("times_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Menu.
        /// </summary>
        internal static string toggle_menu {
            get {
                return ResourceManager.GetString("toggle_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Toggle button for the Menu to appear or dissapear.
        /// </summary>
        internal static string toggle_menu_description {
            get {
                return ResourceManager.GetString("toggle_menu_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Products.
        /// </summary>
        internal static string view_products {
            get {
                return ResourceManager.GetString("view_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, .
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your codes are:.
        /// </summary>
        internal static string your_codes_are {
            get {
                return ResourceManager.GetString("your_codes_are", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use these codes on thephotoshop.nl when creating an account..
        /// </summary>
        internal static string your_codes_description {
            get {
                return ResourceManager.GetString("your_codes_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your codes from The Photoshop.
        /// </summary>
        internal static string your_order_codes {
            get {
                return ResourceManager.GetString("your_order_codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipcode.
        /// </summary>
        internal static string zipcode {
            get {
                return ResourceManager.GetString("zipcode", resourceCulture);
            }
        }
    }
}
